ALTER TABLE tiendas
  ADD COLUMN IF NOT EXISTS radio_entrega_km INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS latitud          DECIMAL(10,8) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS longitud         DECIMAL(11,8) DEFAULT NULL;
